openapi: 3.0.0
info:
  title: Your API Title
  version: 1.0.0
  description: API Documentation for your application
servers:
  - url: http://localhost:80 # Change to your server URL

paths:
  /api/auth/register:
    post:
      summary: Register a new user
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
                role:
                  type: string
                  enum: [user, admin]
      responses:
        '200':
          description: Registration successful
        '500':
          description: Internal server error

  /api/auth/login:
    post:
      summary: Login an existing user
      tags:
        - Auth
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '404':
          description: User not found
        '401':
          description: Incorrect password

  /api/authenticate:
    post:
      summary: Check user authentication
      tags:
        - Auth
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Authenticated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  user:
                    type: object
                    properties:
                      username:
                        type: string
                      email:
                        type: string
                      role:
                        type: string
        '401':
          description: Authentication required
        '404':
          description: User not found
        '403':
          description: Invalid token

  /api/dashboard:
    get:
      summary: Get dashboard data
      tags:
        - Dashboard
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Dashboard data retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                  user:
                    type: object
                    properties:
                      username:
                        type: string
                      role:
                        type: string
        '403':
          description: Access denied
        '401':
          description: Authentication required

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
